# Generated by Django 4.1.6 on 2023-04-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_orderupdate_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PACKING', 'Packing'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received at nearby hub'), ('DELIVERED', 'Delivered')], default='New', max_length=15),
        ),
    ]
